# Generated by Django 3.2.7 on 2021-10-29 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraccount_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersHeroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('STR', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('CON', models.IntegerField()),
                ('INT', models.IntegerField()),
                ('WIS', models.IntegerField()),
                ('CHA', models.IntegerField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
