# Generated by Django 3.2.7 on 2021-11-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211102_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersheroes',
            name='class_type',
            field=models.IntegerField(choices=[(0, 'barbarian'), (1, 'bard'), (2, 'clerif'), (3, 'druid'), (4, 'fighter'), (5, 'monk'), (6, 'paladin'), (7, 'ranger'), (8, 'rogue'), (9, 'sorcerer'), (10, 'warlock'), (11, 'wizard')]),
        ),
        migrations.AlterField(
            model_name='usersheroes',
            name='race_type',
            field=models.IntegerField(choices=[(0, 'dragonborn'), (1, 'dwarf'), (2, 'elf'), (3, 'gnome'), (4, 'half-elf'), (5, 'half-orc'), (6, 'halfling'), (7, 'human'), (8, 'tiefling')]),
        ),
    ]
