# Generated by Django 3.2.7 on 2021-11-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211102_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersheroes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
