# Generated by Django 3.2.7 on 2021-11-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_usersheroes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersheroes',
            name='class_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersheroes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersheroes',
            name='race_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
