# Generated by Django 3.2.7 on 2021-11-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211102_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersheroes',
            name='class_type',
            field=models.IntegerField(choices=[('barbarian', 'barbarian'), ('bard', 'bard'), ('clerif', 'clerif'), ('druid', 'druid'), ('fighter', 'fighter'), ('monk', 'monk'), ('paladin', 'paladin'), ('ranger', 'ranger'), ('rogue', 'rogue'), ('sorcerer', 'sorcerer'), ('warlock', 'warlock'), ('wizard', 'wizard')]),
        ),
    ]
