# Generated by Django 3.2.7 on 2021-11-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_useraccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='chat_pass',
            field=models.CharField(default='password', max_length=255),
        ),
    ]
