# Generated by Django 3.2.7 on 2021-11-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211102_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersheroes',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='usersheroes',
            name='race_type',
        ),
    ]
