# Generated by Django 3.2.7 on 2021-11-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211103_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersheroes',
            name='class_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersheroes',
            name='race_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
